name: flexible_scrollable_table_view
description: A table view who can scroll both vertical and horizontal.
version: 2.7.1
homepage: 'https://github.com/AAAAAApril/flexible_scrollable_table_view'

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

# 发布插件命令
# flutter packages pub publish --server=https://pub.dartlang.org
